import type { Metadata } from 'next'
import { PT_Serif_Caption } from 'next/font/google'
import { Lora } from 'next/font/google'
import '../styles/styles.scss'
const serif = Lora({
  subsets: ['latin'],
  weight: '400'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${serif.className} bg-black`}><main className="mt-[100px] p-[20px]">{children}</main></body>
    </html>
  )
}