import type { Metadata } from 'next';
import { Cormorant, Libre_Baskerville, Lora, Noto_Serif_Ahom, Playfair_Display, Stalinist_One } from 'next/font/google';
import { Tooltip, TooltipProvider } from '@/components/ui/tooltip';
import '../styles/styles.scss';

const serif = Libre_Baskerville({
  subsets: ['latin'],
  weight: ['400', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (

        <html lang="en">
          <body className={`${serif.className} bg-white`}>
            <main className="mt-[100px] p-[20px]">{children}</main>
          </body>
        </html>

  );
}