import { Inter } from "next/font/google";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '700'],
});
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html className={`${inter.className} dark text-foreground bg-background`} lang="en">
      <body className=' pb-20 min-h-screen flex'>
        {children}
      </body>
    </html>
  )
}

